### ISSUE TITLE
Add copyright information to neomutt-test-files

### ISSUE THREAD

**Issue by charles2910** [neomutt/neomutt-test-files#4]
Hi!

It would be really nice to have copyright information on this repo, I'm assuming it's the same as neomutt, but it's better to have it written down :-)

**Comment by flatcap** [comment]
Good call.
Done: [7404f44](https://github.com/neomutt/neomutt-test-files/commit/7404f4423b11cd5da2d123b3636c7a310bbbed9f)

Thanks
